export { default as logo} from "./utkal logo.svg"
export { default as home1} from "./banner.png"
export { default as chintu} from "./IMG_20241231_160308.jpg"
export { default as home2} from "./2.png"
export { default as footer} from "./recent-2.jpg"
export { default as Image} from "./digital-marketing-media-globe-shape-business-business-man-hand-working-laptop-computer-tablet-smart-phone-office-132113579.jpg"
export { default as home13} from "./Z+Security_Icon.png"
export { default as home14} from "./Artboard 8.png"
export { default as smartlink} from "./Smart_Link blue.png"
export { default as home15} from "./utkal facility.png"
export { default as corporation} from "./utkal corporation.png"
export { default as ayushman} from "./Ayushman-Logo-Horizontal.png"
export { default as bottling} from "./utkal bottling.png"
export { default as international } from "./utkal international.png"
export { default as education} from "./utkal education.png"
export { default as education1} from "./utkaleducation.jpg"
export { default as global} from "./utkal global.png"
export { default as homes} from "./utkal home.png"
export { default as odo} from "./ODO.png"
export { default as mr} from "./mr new logo.png"
export { default as maxim} from "./maxim logo png.png"
export { default as maxim1} from "./Slider-Image-3-scaled-600x400.jpeg"
export { default as group} from "./utkal group.png"
export { default as homebg} from "./bg.png"
export { default as home16} from "./3.9cf9b3dd.jpg"
export { default as home17} from "./payroll-management.100b7606.jpg"
export { default as home18} from "./staffing.b9f6001b.jpg"
export { default as home19} from "./contact-us-concept-illustration_114360-3147.jpg"

export { default as client1} from "./1-removebg-preview.png"
export { default as client2} from "./2-removebg-preview.png"
export { default as client3} from "./3-removebg-preview.png"
export { default as client4} from "./Untitled_design__11_-removebg-preview.png"
export { default as client5} from "./Untitled_design__9_-removebg-preview.png"

export { default as home26} from "./4-bg.jpg"
export { default as home27} from "./about.jpg"
export { default as home28} from "./chairman__1_-removebg-preview.png"
export { default as zplus} from "./portrait-male-security-guard-with-radio-station-camera-screens.jpg"
export { default as indo1} from "./Screenshot 2024-11-07 131020.png"
export { default as bottle} from "./utkal bottling.png"
export { default as ayush1} from "./Picture4.jpg"
export { default as odo1} from "./Picture7.png"
export { default as utkal1} from "./utkal global.png"
export { default as facility} from "./utkalfacility.png"
export { default as power} from "./AdobeStock_618717616-scaled.jpeg"
export { default as national} from "./coffee.jpg"
export { default as myjob} from "./Picture13.png"
export { default as job1} from "./MYJOB_LOGO_HORIZONTAL.png"
export { default as homedeal} from "./Leverage-effective-real-estate-marketing-materials-to-attract-qualified-buyers-to-your-luxury-homes.jpg"
export { default as corporation1} from "./utkalcorporation.jpg"
export { default as power1} from "./utkal power.png"
export { default as house} from "./utkal home.png"
export { default as logo1} from "./WhatsApp_Image_2025-10-06_at_10.29.32_090d041a-removebg-preview.png"

export { default as client6} from "./2.3d2ae6b8.png"
export { default as client7} from "./17.2ae774f4.png"
export { default as client8} from "./12.4c9d4538.png"
export { default as client9} from "./24.bedc49c9.png"
export { default as client10} from "./26.72f4ad81.png"
export { default as client11} from "./29.bcef4722.png"
export { default as client12} from "./39.00e29fcc.png"
export { default as client13} from "./40.d4d9966f.png"
export { default as slider1} from "./df8d694c-6289-4bc2-9f12-ab203263976b.jpg"
export { default as slider2} from "./Animated Social Media in Cream Black Stylenew.jpg"
export { default as slider3} from "./ca0ac78d-667c-4cff-9fff-ae8368ae59f7.jpg"
export { default as slider4} from "./utkalpower.png"
export { default as slider5} from "./istockphoto-671580286-612x612.jpg"
export { default as slider6} from "./gettyimages-1552781935-612x612.jpg"
export { default as slider7} from "./utkal-facility-services-image-1.5b42da53.jpg"
export { default as slider8} from "./utakalindopluds.png"
export { default as slider9} from "./about-banner.jpg"
export { default as slider10} from "./Slider-Image-3-scaled-600x400.jpeg"
export { default as slider11} from "./utkalglobal.jpg"
export { default as slider12} from "./mrcorporate.png"
export { default as slider13} from "./utkalsmartlink.png"
export { default as slider14} from "./utkalayushman.png"
export { default as slider15} from "./education-background-with-flat-elements_1302-837.jpg"
export { default as mr1} from "./mr new logo.png"
export { default as utkalz} from "./Z+Security_Icon_White.0d0aa187.png"
export { default as joblogo} from "./MYJOB_LOGO_ICON.png"
export { default as foundation} from "./utkal foundation.png"
export { default as topfront} from "./Topfront Logo1.0a2a0957.png"
export { default as top} from "./slider2.c222f192.jpg"
export { default as ayus1 } from "./slider-1.jpeg"
export { default as smart} from "./utkal smart.png"
export { default as found} from "./utkal foundation.jpg"
export { default as global1} from "./global.png"
export { default as link} from "./smartlink-pic.png"
export { default as study} from "./1000_F_98495191_5TZhGHhv14cINtalgHiQyCH1bApk7HQ3.jpg"
export { default as top1} from "./Engineering.a027aac3.jpg"
export { default as max} from "./1622887648434.jpg"
export { default as bott} from "./bottling.png.jpg"
export { default as MainLogo} from "./Artboard 4-100.jpg"

